CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'client') THEN
        CREATE SCHEMA client;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'customer') THEN
        CREATE SCHEMA customer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'review') THEN
        CREATE SCHEMA review;
    END IF;
END $EF$;

CREATE TABLE client.channel (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    code character varying(250),
    name character varying(250),
    description character varying(250),
    allowed_send_sms boolean NOT NULL,
    is_active boolean NOT NULL DEFAULT (false),
    survey_id bigint,
    company_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    created_by bigint,
    updated_at timestamp with time zone,
    updated_by bigint,
    is_deleted boolean NOT NULL DEFAULT (false),
    ttl timestamp with time zone,
    row_version bytea,
    CONSTRAINT "PK_channel" PRIMARY KEY (id)
);

CREATE TABLE customer.customer (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(250),
    mobile character varying(250),
    company_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    created_by bigint,
    updated_at timestamp with time zone,
    updated_by bigint,
    is_deleted boolean NOT NULL DEFAULT (false),
    ttl timestamp with time zone,
    row_version bytea,
    CONSTRAINT "PK_customer" PRIMARY KEY (id)
);

CREATE TABLE client.location (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100),
    instashop_client_id character varying(250),
    instashop_average_rating double precision NOT NULL,
    is_active boolean NOT NULL DEFAULT (false),
    last_scrape_attempt_time timestamp with time zone,
    last_successful_scrape_time timestamp with time zone,
    company_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    created_by bigint,
    updated_at timestamp with time zone,
    updated_by bigint,
    is_deleted boolean NOT NULL DEFAULT (false),
    ttl timestamp with time zone,
    row_version bytea,
    CONSTRAINT "PK_location" PRIMARY KEY (id)
);

CREATE TABLE review.source_review_summary (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    instashop_avg_rating double precision,
    instashop_total_responses integer,
    date date NOT NULL,
    location_id bigint NOT NULL,
    avg_rate double precision NOT NULL,
    total_responses bigint NOT NULL,
    company_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    created_by bigint,
    updated_at timestamp with time zone,
    updated_by bigint,
    is_deleted boolean NOT NULL DEFAULT (false),
    ttl timestamp with time zone,
    row_version bytea,
    CONSTRAINT "PK_source_review_summary" PRIMARY KEY (id)
);

CREATE TABLE client.location_channel (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    channel_id bigint NOT NULL,
    location_id bigint NOT NULL,
    is_qr_code_active boolean NOT NULL,
    is_channel_active boolean NOT NULL,
    qr_code_text character varying(250),
    company_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    created_by bigint,
    updated_at timestamp with time zone,
    updated_by bigint,
    is_deleted boolean NOT NULL DEFAULT (false),
    ttl timestamp with time zone,
    row_version bytea,
    CONSTRAINT "PK_location_channel" PRIMARY KEY (id),
    CONSTRAINT "FK_location_channel_channel_channel_id" FOREIGN KEY (channel_id) REFERENCES client.channel (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_location_channel_location_location_id" FOREIGN KEY (location_id) REFERENCES client.location (id) ON DELETE RESTRICT
);

CREATE TABLE client.review (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    source integer NOT NULL,
    rate integer NOT NULL,
    feedback character varying(250),
    reviewer_name character varying(250),
    published_at timestamp with time zone,
    scraped_at timestamp with time zone,
    review_date Date NOT NULL,
    location_id bigint,
    location_name character varying(250),
    sentiment character varying(250),
    is_processed boolean NOT NULL,
    company_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    created_by bigint,
    updated_at timestamp with time zone,
    updated_by bigint,
    is_deleted boolean NOT NULL DEFAULT (false),
    ttl timestamp with time zone,
    row_version bytea,
    CONSTRAINT "PK_review" PRIMARY KEY (id),
    CONSTRAINT "FK_review_location_location_id" FOREIGN KEY (location_id) REFERENCES client.location (id) ON DELETE RESTRICT
);

CREATE INDEX "IX_location_channel_channel_id" ON client.location_channel (channel_id);

CREATE INDEX "IX_location_channel_location_id" ON client.location_channel (location_id);

CREATE INDEX "IX_review_location_id" ON client.review (location_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260118161602_Initial', '9.0.1');

COMMIT;

